### PR TITLE
Force nonstd string_view and span to fix C++17/20 interop

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fix: #398

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Another thing:
I get a ASAN ODR violation for

``dbarray.cpp:15 constexpr DBArrayAlloc::size_type DBArrayAlloc::_empty_buf;``

When I comment this out liblcf still works here and the error is gone. Opinion?

**Comment by fmatthew5876** [comment]
That sound fix it, this was a real bug. I'm surprised my use of asan didn't catch it.

**Review by Ghabry — APPROVED** [review]
works for me

**Comment by Ghabry** [comment]
ASAN doesn't complain anymore but it still fails on Jenkins (Editor-Qt):

```
/bin/ld: /var/lib/jenkins/workspace/liblcf-linux/build/lib/liblcf.a(liblcf_la-dbarray.o):(.rodata+0x8): multiple definition of `lcf::DBArrayAlloc::_empty_buf'; libEasyRPG_Editor.a(main_window.cpp.o):(.rodata._ZN3lcf12DBArrayAlloc10_empty_bufE[_ZN3lcf12DBArrayAlloc10_empty_bufE]+0x0): first defined here
collect2: error: ld returned 1 exit status
```

:(

**Pull request merged**
