### PR TITLE
Add ForEachString

### PR DESCRIPTION
**Pull request by Ghabry**
This adds a new function ``ForEachString`` for replacing strings in LCF. Used for translation as discussed in that Player PR.

CC @sorlok

### CODE REVIEW

**Comment by fmatthew5876** [comment]
1. I would change the lambda to not have a return value, then I can write these:


```
[](auto& field, const auto& name) { field = transform(field); };
[](auto& field, const auto& name) { Utils::ToUpperInplace(field); };
[](const auto& field, const auto& name) { doSomethingReadOnly(field); };
```

This also grants some potential efficiency as you can modify the already allocated string object in place and not create a new one with a return value.


2. Also, the name is not enough information. Inside my lambda, you give me the name of the field but I don't which struct it is. I would also pass in the struct itself.

```
f(*this, name, "name");
```

3. Consider making `ForEachString()` a free function overloaded for all rpg types instead of a member function. That makes it easier to extend to other types.

**Comment by Ghabry** [comment]
What is "a free function overloaded for all rpg types". (I only know overloading in the context of class inheritance)

Do you mean a template function with specialization per rpg type?

**Comment by fmatthew5876** [comment]
```
template <typename F>
void ForEachString(lcf::rpg::SaveActor&, const F& f);
template <typename F>
void ForEachString(lcf::rpg::SaveMapEvent&, const F& f);
```
 etc..

Don't template the struct type, C++ already gives us function overloading to do that.

**Comment by Ghabry** [comment]
Another use case: Reencoding the entire database without parsing again (at least once, for "Unknown -> Detected")

**Comment by sorlok** [comment]
So right now you get the property's name ("end_game") and the value ("Shutdown"). When looking this up in the .po files, we actually look up by context ("term"). See sample code below.

```
	// Translate all terms
	lcf::Data::terms.ForEachString([this](const std::string& value, const std::string& name)->std::string {
		if (sys!=nullptr) {
			return sys->translate_ctxt("term", value);
		}
		return value;
	});
```

I think the following changes make sense:
1) Pass the context ("term") in to the callback function as well. This streamlines translation substitution.
2) Switch the order of name and value (stylistic)
3) Pass the value in by NON-const reference, so we don't *have* to always overwrite it.

**Comment by fmatthew5876** [comment]
> Another use case: Reencoding the entire database without parsing again (at least once, for "Unknown -> Detected")

So you mean we don't have to load the entire database twice?? That'll be a huge win for player!

**Comment by sorlok** [comment]
One other thing to consider (in addition to my comment above)  ---right now, if you switch from Default language to Spanish, then from Spanish to French, I have to reload the database (so that we can look up strings properly). I don't think this is worth fixing, since switching between multiple languages at runtime is an edge use case. Just to make sure everyone's aware though.

**Comment by Ghabry** [comment]
> So you mean we don't have to load the entire database twice?? That'll be a huge startup time performance win for player!

Yeah exactly this. See #169

> So right now you get the property's name ("end_game") and the value ("Shutdown"). When looking this up in the .po files, we actually look up by context ("term"). See sample code below.

matthew already suggested to also provide an object instance. You can use the object instance to get a name through "reflection": ``Struct<std::remove_reference_t<decltype(instance)>>::name``. But this is 1. not public API and 2. uglyyyy. Maybe add some ``lcf/reflection.h`` header which abstracts this stuff (``GetTypename(rpg::instance&)``, also add ``ForEachString`` there), then we can freely alter the templates later without breaking code.
CC @fmatthew5876 You are the template master here (I needed 10 minutes to make this ``Struct`` line compile ;)). thoughts?

**Comment by sorlok** [comment]
The "reflection" idea sounds fine to me. I also like that LcfTrans can be updated to always be in sync on these contexts.

Is there any case where the name of the "context" (passed in to getText()) would need to be very different from the name of the class? That's the only thing I can think of that might trip this up. So far, I can't think of any case where this would be true.

**Comment by fmatthew5876** [comment]
`Struct<std::remove_reference_t<decltype(instance)>>::name`

Reader struct is not part of the public API, and it never should be. 

What I think we need here is a new reflection mechanism that is public, and refactor reader_struct to use it.

**Comment by sorlok** [comment]
Hi, just checking in. Should I wait for the refactoring to ForEachString() or continue coding with the current API? (This is for the Translation PR I'm working on.) I've still got lots of side stuff to do, so no rush.

**Comment by fmatthew5876** [comment]
I looked into proper reflection, it got way over complicated too fast. Also compile times doubled.

Since our main problem is just being able to translate strings, I suggest we move forward with this for now. You could just pass in the struct name and member name as string literals.

**Comment by Ghabry** [comment]
closing in favor of #394

**Comment by Ghabry** [comment]
@sorlok 

Please wait a bit more. I will ping you when it is ready.

**Pull request closed without merging**
