### PR TITLE
Change Korean and Japanese encodings to fix file finding errors

### PR DESCRIPTION
**Pull request by fdelapena**
Fixes EasyRPG/Player#649

ICU from toolchains will need to be rebuilt to make this update work properly.

After updating toolchains also closes EasyRPG/Player#746

### CODE REVIEW

**Comment by Ghabry** [comment]
Is that encoding not supported in the static toolchains? :(

**Comment by fdelapena** [comment]
Not tested, the icudata demo should explain codepage dependencies better. I can check it tonight.

**Comment by carstene1ns** [comment]
datfile

**Comment by Ghabry** [comment]
You can now embed word documents to github comments iirc. So you can embed "dat file" in the word document and upload that one :D

**Comment by fdelapena** [comment]
Here is the [.dat download](https://fran.cr/owncloud/index.php/s/Z4FqmlqS2z2iiRX/download) link, for ICU56

**Comment by Ghabry** [comment]
[datfile.docx](https://github.com/EasyRPG/liblcf/files/39229/datfile.docx)

**Comment by fdelapena** [comment]
After further testing, yet another issue. This time with middle dot conversion into UTF-8:

When trying to read some file with middle dot, we have 2 possibilities, depending on encoding:
U+00B7 · middle dot (windows-949-2000, uses backslash)
U+30FB ・ katakana middle dot (ibm-1363_P110-1997, uses Won)

Test: `--encoding windows-949-2000 --start-map-id 11 --new-game`

Not sure which filename is the right on real win32 RTP, as online decoders might have differ from real Win9x. At least after using convmv to unpack the zip, it needs windows-949-2000 to load this file properly.

**Comment by carstene1ns** [comment]
time to get a windows 98 vm ready :grinning:

**Comment by fdelapena** [comment]
Can't test this until Player#673 is fixed.

**Comment by fdelapena** [comment]
After unpacking a zip using Korean locale on Windows, it seems to use U+00B7, so windows-949-2000 (with \ ) is the current candidate.

**Comment by Ghabry** [comment]
Is this still pending fix?

**Comment by fdelapena** [comment]
> Is this still pending fix?

Fixed, tested and ready.

**Comment by fdelapena** [comment]
Don't merge yet, it looks like Japanese encoding will need an update too... it does not detect filanemes with ～ properly and the new encoding kills backslash to yen conversion :sob:.

**Comment by fdelapena** [comment]
Jenkins: retest this please

**Comment by fdelapena** [comment]
Ready for your ICU rebuilds. ^^

**Pull request merged**
