### PR TITLE
Remove lcf::Data

### LINKED ISSUE #305: Wrong event page variable condition when writing emu to lmu
RPG Maker version: 2003 1.12a
Lastest nightly liblcf in LCF2XML (Jan24 2019).

When you convert a map with a event that contains a tab with a variable condition from EMU to LMU (LMU to EMU is fine), the condition is changed.

Here's a test case:
We have this condition in a map.
image

Then after converting the map from LMU to EMU, and then back to LMU with LCF2XML, the condition changes to this one:
image

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depended by: https://github.com/EasyRPG/Player/pull/2404
Depended by: https://github.com/EasyRPG/Editor-Qt/pull/150

Fix #305

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Review by Ghabry — COMMENTED** [review]
How about making SaveOpt a non-optional param and adding 2k3 as a SaveOpt?

**Comment by fmatthew5876** [comment]
I'm on the fence about that. I kind of feel this flag is so important it should stand on it's own so you're forced to think about it and set the right value. Also it's not used for `LDB_Reader`.

I could be convinced otherwise though

**Comment by Ghabry** [comment]
Instead of only adding Engine2k3 one could also make the functions hard fail (assert?) when the ``SaveOpt`` is not set.

Add ``Engine2k`` and ``Engine2k3`` to it and check for the existence.

If you don't like this: I would prefer, instead of the ``2k3 bool`` to have an engine enum here. Then this can be extended if we decide to to e.g. only write fields when the engine is ``EasyRpg``.

**Comment by fmatthew5876** [comment]
Changed the bool to an enum, I agree this is better.

Once this PR is approved, I will update Player and Editor PRs

**Comment by Ghabry** [comment]
on first glance this looks fine. Reviewing it tomorrow, thanks.

**Review by fdelapena — APPROVED** [review]

**Review by Ghabry — APPROVED** [review]
waiting for the other PR updates before merging this

**Comment by fmatthew5876** [comment]
All PRs updated, this is ready now

**Pull request merged**
