### PR TITLE
Change battle_commands type to vector<int32_t>

### PR DESCRIPTION
**Pull request by Ghabry**
and changed the initialisation to match @20kdc observations.

This breaks compiling of the Player (Build failure issues are coming \*g\*):

```diff
diff --git a/src/game_actor.cpp b/src/game_actor.cpp
index c97415c2..c6c62242 100644
--- a/src/game_actor.cpp
+++ b/src/game_actor.cpp
@@ -940,7 +940,7 @@ void Game_Actor::ChangeBattleCommands(bool add, int id) {
 		GetData().battle_commands.clear();
 	}
 	else {
-		std::vector<uint32_t>::iterator it;
+		std::vector<int32_t>::iterator it;
 		it = std::find(GetData().battle_commands.begin(), GetData().battle_commands.end(), id);
 		if (it != GetData().battle_commands.end())
 			GetData().battle_commands.erase(it);
```

### CODE REVIEW

**Comment by Ghabry** [comment]
Shall I rename ``class_changed`` to ``battle_commands_changed``?

**Comment by carstene1ns** [comment]
Yes, as it is more fitting the observations.

**Comment by carstene1ns** [comment]
This breaks on Vita, Wii and 3DS unfortunately, as there is no template for `long` type... wupps.

**Comment by Ghabry** [comment]
hmmm, guess fixing this will be quite complex because the liblcf currently mixes int32_t and int ^^'. Have to change all int-types to int32_t or change the battle commands vector to int... The first is imho the correct way and the second the easy way.

**Pull request merged**
