### PR TITLE
Add Maniac patch chunks

### PR DESCRIPTION
**Pull request by Ghabry**
TODO:

- ~~For ``ManiacEventInfo`` figure out what the ``was*`` things are~~
- ~~Still some unknown chunks, waiting for BingShan reponse~~

### CODE REVIEW

**Comment by Ghabry** [comment]
maniac_event_info, maniac_event_page and maniac_event_id are kinda broken. Guess this was fixed later in a non-released version.
Anyway I consider them very useful for debug purposes, we could also populate them with sane values.

**Review by fdelapena — APPROVED** [review]

**Review by carstene1ns — APPROVED** [review]
Looks good to me.

**Review by fmatthew5876 — APPROVED** [review]

**Comment by fmatthew5876** [comment]
Looks fine to me, but do we have all these marked as tasks in a Player issue? I don't want to add a bunch of chunks and then we forget we need to add support for them in Player.

**Comment by Ghabry** [comment]
No but this sounds like a good idea, will open a new issue for this as the Maniac issue is already bloated enough ;)

**Pull request merged**
