### PR TITLE
Fix clang warnings about templates

### LINKED ISSUE #221: clang dislikes reader_struct and reader_flags
Lot's of these (122):
```
src/reader_struct.cpp:27:18: warning: instantiation of variable 'Struct<RPG::Actor>::fields' required here, but no definition is available [-Wundefined-var-template]
        for (int i = 0; fields[i] != NULL; i++)
                        ^
./src/reader_struct.h:512:25: note: forward declaration of template entity is here
        static const Field<S>* fields[];
                               ^
src/reader_struct.cpp:27:18: note: add an explicit instantiation declaration to suppress this warning if 'Struct<RPG::Actor>::fields' is explicitly instantiated in another translation unit
        for (int i = 0; fields[i] != NULL; i++)
                        ^
```

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on #289 
Fixes #221 

MSVC chokes on this so I had to split it out. Maybe upgrading to VS2017 will fix it?

### CODE REVIEW

**Comment by carstene1ns** [comment]
IMO we could wait with this until our build agent is updated with vcpkg and MSVC 2017. Maybe is really fixed and does not break the build currently.

**Comment by Ghabry** [comment]
@fmatthew5876 
Compiler is now latest VS2017, try again building under Windows.

**Comment by fmatthew5876** [comment]
Looks like no.

Lets leave this alone for now. There are other ways to refactor the code that should be nicer than some big ugly ifdef. For example, probably changing `Struct::name()` to an inline function will fix it for all platforms.

**Comment by Ghabry** [comment]
a search suggested to use "/permissive-" but I just tested and didn't work either.

**Comment by carstene1ns** [comment]
What I dislike here is that this list is not autogenerated.

jenkins: test this please

**Comment by carstene1ns** [comment]
Closing. Can be reopened when there is a proper solution to this.

**Pull request closed without merging**
