### PR TITLE
Vs2015

### PR DESCRIPTION
**Pull request by Ghabry**
The only supported compiler for Windows is now VS2015 Community (which is freely available, yeah!)

This commit breaks XP support and heavily simplifies project files based on my new knowledge (PropertySheets). Also removes the non-XML build.

(jenkins bot comes back up soon)

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by carstene1ns** [comment]
Seems like ICU is missing.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Hmmmm, have to check this later at my PC. Very strange

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: Test this please <3 ...

**Pull request merged**
