### PR TITLE
Move lcf::Data out of parser implementations

### PR DESCRIPTION
**Pull request by fmatthew5876**
Preparation for removing globals from liblcf. This change only moves `lcf::Data` out to the edges. Player and Editor are not affected by this.

Next PR will remove `lcf::Data`
 
TBD:

- [x] Test reading/writing 2k and 2k3 LDB, LMT, LMU, LSD files to ensure no breaks

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Comment by fmatthew5876** [comment]
I tested this on some lcf files, the outputs match exactly. This is ready.

**Comment by Ghabry** [comment]
did you use this 1500 LDB files collection from rmarchiv?

I wanted to run a test with them but somehow can't find the script anymore.
I slowly consider setting up a test on jenkins that does this for me...

**Comment by fmatthew5876** [comment]
I have about 40 games 2k and 2k3 on my hard drive right now.
I just made `bench_readldb` save the ldb back to disk and ran this:

`for x in 2k3/*/*.ldb; do ./bench_readldb "$x"; md5sum "$x" out.ldb; done`

All compared exactly.

**Comment by Ghabry** [comment]
2269 LDB, 2269 LMT, 4229 LMU and 722 LSD later: The hashes match. (also the mismatches match, more on this later)

**Review by Ghabry — APPROVED** [review]

**Pull request merged**
