### PR TITLE
Bitperfect copying of LSD

### LINKED ISSUE #246: List of games which can't be copied perfectly by liblcf
This issue is to list games can't be copied LDB -> LDB cleanly by liblcf

RM2k Games:
* Bloodmoon Ent. & Hangman - 2k game but the ldb_id == 2003. RPG::Terms 0x1, 0x26, and 0x27 are written out with 2k3 behavior.
* Der Sinn des Lebens (Demo 2) - Corrupted animation chunk??
* Devil and Angel - Animation 31: "Nebbia B" is corrupted. The chunk doesn't terminate properly and Liblcf reads past the length of the block and messes everything up. RM2k seems to be able to load the ldb but the animation in the rm2k editor has bogus data.
* Fate Hunter Oreleon - One animation has Cell x repeated twice - only last one is used and written back out.
* Kroetenstuhl - Corrupted animation data 
* Rick Jones Hunters - Corrupted animation data
* Sweet Dreams (Demo) - ldb is padded with 10 extra 0's at the end??

RM2k3 Games:
* Antagonism - ldb_id == 2003 but missing Terms 0x26 and 0x27. Should be present. Maybe converted from 2k?
* Aliens - This Time it's War (Demo) - Terms 0x26/0x27 missing
* Bloody Baster's Killer Instinct v1.02 - Terms 0x1/0x3 present
* Budubi's Scary School - Terms 0x1/0x3 present, 0x26/0x27 missing
* Budubi's Scary School (Final Mix)- Terms 0x1/0x3 present, 0x26/0x27 missing
* Die Abenteuer der MS White - Terms 0x26/0x27 missing
* Dragonball V - Terms 0x26/0x27 missing
* Echos of the Past - Terms 0x26/0x27
* ~Haematom - Terms 0x26/0x27
* Im Tal des Schreckens 3 (Demo) - Terms 0x26/0x27
* In den Wolken - Terms 0x26/0x27
* Koma Klaus - Terms 0x26/0x27
* Mario and Luigi - Lugmillas Return - Terms 0x3,0x26,0x27
* Mario's Older Brother - Corrupt headers, Terms 0x1,0x3,0x26,0x27
* Monster World RPG - Appears to be much corruption. Need to investigate further.
* Seven Blades - Darkness (v0.41) - Many differences - investigate further.
* Space Drop - The hero myth - Terms 0x26,0x27
* Space Drop - The Hero Myth (Demo) - Terms 0x26,0x27
* Wir Beide - Terms 0x26,0x27

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fixes #246

This series of changes is towards doing perfect copies of LSD files.

So far I am able to copy a few local save games I have. 

If anyone has lots of saved games, please test copying with this branch of send the saves to me.

### CODE REVIEW

**Comment by fmatthew5876** [comment]
Thanks for those saves, I was able to fix a few more things.

I checked them all and only these are remaining:

* Der Brief für den König - Demo II (Ver1.4) - Kopie - This is in your 2k/ folder but it has 2k3 battle_commands. When processed as a 2k3 game the lsd's copy cleanly.
* Dark Sword - Demo 2.1.2/Dark Sword II Remake/Save15.lsd - One picture has SavePicture::transparency = 96. This is a boolean field so our code converts it to 1 and writes it back out as 1. The picture text is `DynResource\MessageBox\EmptyPixel.png`. Could this be a third party patch?


This test and PR doesn't mean we write LSD files correctly. I only tested copying them from one file to another, not actually saving with player. For my test, I had to hack `Data::system.ldb_id = 2003` to make the the 2k3 games copy correctly.

**Comment by CherryDT** [comment]
Yes looks like some dynrpg Plugin taking advantage of the fact that a bool is just saved and loaded as one byte in memory and puts more stuff into the same byte

**Comment by Ghabry** [comment]
We can declare Dark Sword as "completely incompatible", uses too many DynRPG plugins. DynRPG was a mistake :P

The other one: Will check later if this is another case of wrong engine detection like .flow

**Comment by Ghabry** [comment]
(feel free to put LMU fixes in this PR, makes the testing easier for me)

**Comment by fmatthew5876** [comment]
> 
> 
> (feel free to put LMU fixes in this PR, makes the testing easier for me)

Sure, let me know any games with LMU failures and I'll investigate and add here,

**Comment by fmatthew5876** [comment]
I've also removed the save count dependency. So you don't need to worry about that messing up your test results here.

**Comment by Ghabry** [comment]
Okay, I got a small amount of LDBs and LMTs more and had to delete ~30 LMUs because the LDB was missing for some reason which means the test wouldn't make sense.

```
LDB Test results for 1551 files

Summary:
2k:   1089/1089 (100.0%)
2k3:  416/416 (100.0%)
2k3e: 46/46 (100.0%)

LMT Test results for 1550 files

Summary:
2k:   1088/1088 (100.0%)
2k3:  416/416 (100.0%)
2k3e: 46/46 (100.0%)

LMU (Map0001) Test results for 1518 files

./2k/(Demo3)The Fuc. Schrank (V 3.0.3)
./2k/Aliminator -VV 1.02 - Kelven - 2k- 13.08.2003
./2k/DBL2
./2k/Der Feind (Demo 2)
./2k/The History of Planet Bryyo - First Conflict (v1.04)
./2k/Yoshis Maze Mania (v1.10)
./2k3/Colourway1.01
./2k3/Die letzte Grenze (Beta)
./2k3/Duckworld 2 [2k3] (v2.0)
./2k3/Duckworld 3 [2k3] (v0.60)
./2k3/Duckworld [2k3] (v1.1)
./2k3/Fog over Esidar (Demo)
./2k3/Raus aus dem Dungeon
./2k3/Super Peach RPG (Demo)
./2k3/The Legend of Phylandia (Demo)

Summary:
2k:   1062/1068 (99.4%)
2k3:  396/405 (97.8%)
2k3e: 45/45 (100.0%)

LSD Test results for 358 files

./2k3/Dark Sword - Demo 2.1.2/Dark Sword II Remake

Summary:
2k:   179/179 (100.0%)
2k3:  176/177 (99.4%)
2k3e: 2/2 (100.0%)
```

My script also collects the failing files now:
[failed.zip](https://github.com/EasyRPG/liblcf/files/2526712/failed.zip)

**Comment by fmatthew5876** [comment]
It looks like all generator chunks (even arrays) dissapear when defaulted. So that fixed a few 2k3 games. Also I found some of the 2k games have generator chunks their maps. Since all generator chunks disapear when defaulted, I've disabled is2k3 on them. Now any map from any version will just passthrough whatever generator chunks it may have.



The following games have 2 extra bytes after the Map data ends. I don't know if this is corruption or custom patch hackery. These bytes are placed after the terminating 0 and so liblcf does not read them.

```
./2k/Aliminator -VV 1.02 - Kelven - 2k- 13.08.2003 - 5C10
./2k/DBL2 - 5C10
./2k/Der Feind (Demo 2) - 1B34
./2k/Yoshis Maze Mania (v1.10) - 010C
```

**Comment by fmatthew5876** [comment]
While testing Violated Heroine for the other PR, I found it's LDB doesn't copy cleanly. There is something really strange.

This LDB has a 7 character string "Unknown" for Skill chunk 0x7 `failure_message`. Failure message is supposed to be an integer reffering to one of the skill failure message types.

liblcf tries to interpret it as a 7 byte integer and throws up an error.

Has anyone seen this before? Did some version or patch of rm2k store a string in `failure_message`?

**Comment by CherryDT** [comment]
> This LDB has a 7 character string "Unknown" for Skill chunk 0x7 `failure_message`. Failure message is supposed to be an integer reffering to one of the skill failure message types.

It is amazing what kind of oddities you keep digging up. 😲 
No I never heard of anything like this and it makes no real sense to me. I tried looking for the game online because I wanted to see if RPG_RT is patched somehow but I wasn't able to find a working download.

**Comment by Ghabry** [comment]
Only thing I can say is that VH1 doesn't use the battle system at all.

try searching for "VH1", the downloads are usually hosted on mega iirc and the password is "nanako" (or "Nanako")

**Comment by fmatthew5876** [comment]
So for my testing this all looks good.

@Ghabry could you run your script one more time to just sanity check? If it passes then I think we're done here.

**Comment by fmatthew5876** [comment]
Let's merge it :+1

**Comment by Ghabry** [comment]
Another corner case is probably games that use a bogus engine translation that translated (OFF) in Music & Sound with something else, but doesn't seem to affect any of the games here.

**Comment by fmatthew5876** [comment]
Would that not break RPG_RT when it tries to find some bogus filename?

Either way once we have automated testing setup with Jenkins it would be good to add more games to the test set.

**Comment by CherryDT** [comment]
Bogus sounds are ignored. Only bogus sprites crash. It's just that the special effect of turning off other sounds wouldn't work.

**Comment by Ghabry** [comment]
The Player has an heuristic to detect other forms of "(OFF)" btw., so in player this is no issue.

**Pull request merged**
