### PR TITLE
Make more hardcoded terms customizable

### PR DESCRIPTION
**Pull request by rueter37**
Requirement for [Player#2502](https://github.com/EasyRPG/Player/pull/2502)

This PR adds the following database settings:
- Skill option 201 RPG Maker 2003 skill start notification
- Item option 201: Item usage message in battle
- Term 218: RPG Maker 2003 general skill start notification
- Term 219: RPG Maker 2003 general item start notification

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Review by Ghabry — APPROVED** [review]
This looks all useful

**Comment by Ghabry** [comment]
jenkins: test this please

**Comment by Ghabry** [comment]
@rueter37 
could I ask that you shift the chunk ID for Item and Skill by one to the right?

I'm currently thinking about a system to attach "custom game data" to database objects so games can Get/Set this stuff via a new Event command. This is an enhancement over the ugly comment-parsing they do in RPG XP and newer.
For this I would like to reserve chunk 200 for consistency reasons.
(For Terms this does not matter because they are not game data).

**Review by Ghabry — COMMENTED** [review]
Because the player pr has enough approvals I will merge the liblcf side

**Pull request merged**
