### PR TITLE
Use unique_ptr and merge SaveEvents and SaveEventData

### PR DESCRIPTION
**Pull request by Zegeri**
Compilation failures in Player, Editor-Qt and Tools are expected.

### CODE REVIEW

**Comment by carstene1ns** [comment]
c5bcb0b is related to / fixes EasyRPG/Player#553.

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by carstene1ns** [comment]
jenkins: test this please (one more time)

**Comment by Ghabry** [comment]
Looks good to me. As usual for incompatible liblcf changes merge is delayed until a fix for Player is ready.

**Comment by fdelapena** [comment]
59f3ba9 is related to EasyRPG/Player#851.

**Comment by Zegeri** [comment]
0c25adc will be very useful to fix EasyRPG/Player#757.

**Pull request merged**
